--- 
abstract: A bootstrap Perl for building Perl distributions
author: Adam Kennedy <adamk@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perl-Dist-Bootstrap
no_index: 
  directory: 
    - inc
    - t
requires: 
  Perl::Dist: 0.001
  perl: 5.6.0
version: 0.01
